[build]
  # This is where Netlify will look for your site files after building
  publish = "./"
  
  # If you had a build command, it would go here (not needed for your simple HTML site)
  # command = "npm run build"

# This section sets up redirects for clean URLs and SPA support
[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200