[build]
  # This is where Netlify will look for your site files after building
  publish = "./"
  
  # If you had a build command, it would go here (not needed for your simple HTML site)
  # command = "npm run build"

# This section sets up redirects and clean URLs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Clean URLs configuration
[[plugins]]
  package = "netlify-plugin-cache"

# Force pretty URLs (no .html extension)
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
  prettyURLs = true